---
repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        always_run: false
        verbose: false
        pass_filenames: false
        stages:
          - commit
        types:
          - python
        files: ""
      - id: black
        name: Check formatting
        entry: black --check --target-version py310
        language: system
        always_run: false
        verbose: false
        pass_filenames: true
        stages:
          - commit
        types:
          - python
        files: ""
      - id: pytest
        name: pytest
        entry: pytest --quiet
        language: system
        always_run: false
        verbose: false
        pass_filenames: false
        stages:
          - commit
          - push
        types:
          - python
        files: ""
fail_fast: true
